#!/usr/bin/env bash

# shellcheck disable=1091
# shellcheck disable=2086

source "${0%/*}/locations"
source "$UTILITIES/utils.bash"

export _JAVA_AWT_WM_NONREPARENTING=1
export PATH="$PATH:$LIBRARIES"
export BSPDIR

BSPCONFIG="$CONFIG_DIR/bspc/configuration.toml"

function init_workspaces {
	workspaces=$(toml_getpropertylist "$BSPCONFIG" "workspaces.workspace")
	for monitor in `bspc query -M`; do bspc monitor "$monitor" -d $workspaces; done
}

function bspc_config_windows {
	bspc config border_width "$(toml_getproperty "$BSPCONFIG" "windows.window-border")"
	bspc config split_ratio  "$(toml_getproperty "$BSPCONFIG" "windows.window-sratio")"
	bspc config window_gap   "$(toml_getproperty "$BSPCONFIG" "windows.window-gap")"

	bspc config presel_feedback_color "$(toml_getproperty "$BSPCONFIG" "colors.presel-feedback")"

	bspc config focused_border_color  "$(toml_getproperty "$BSPCONFIG" "colors.focused-border")"
	bspc config active_border_color   "$(toml_getproperty "$BSPCONFIG" "colors.active-border")"
	bspc config normal_border_color   "$(toml_getproperty "$BSPCONFIG" "colors.normal-border")"

	bspc config single_monocle true
	bspc config gapless_monocle true
	bspc config borderless_monocle true

	bspc config initial_polarity second_child
	bspc config automatic_scheme longest_side

	bspc config center_pseudo_tiled true
	bspc config remove_disabled_monitors true
	bspc config remove_unplugged_monitors true
}

function bspc_config_pointer {
	bspc config focus_follows_pointer true
	bspc config presel_feedback true

	bspc config pointer_modifier control
	bspc config pointer_action2 resize_side
}

function bspc_config {
	bspc_config_windows
	bspc_config_pointer
}

function update_shortcuts {
	sxhkd -c "$BSPDIR"/configuration/shortcuts/sxhkdrc &

	ksuperkey -e 'Super_L=Alt_L|F1' &
	ksuperkey -e 'Super_R=Alt_L|F1' &
}

function system_runall {
	bspc_runall
	rofi_runall
}

function rofi_runall {
	:
}

function bspc_runall {
	exec "$SCRIPTS_DIR/bspwm/statusbar.sh"
}


init_workspaces
bspc_config

update_shortcuts
system_runall