#!/usr/bin/env bash
source "${0%/*}/locations"

export _JAVA_AWT_WM_NONREPARENTING=1
export PATH="$PATH:$LIBRARIES"
export BSPDIR


function get_workspaces {
	index=1

	while :;
	do
		tmp="$(stoml "$CONFIG_DIR/bspc/configuration.toml" workspaces.workspace-$index)"
		[ -z "$tmp" ] && break
		echo "$tmp"
		let index++	
	done
}

function init_workspaces {
	notify-send "$(get_workspaces)"
	index=1

	for monitor in `bspc query -M`; do
		bspc monitor "$monitor" -n "$index" -d '󰆍'  
		# bspc monitor "$monitor" -n "$index" -d '󰅱' 'test'
		let index++
	done
}

function bspc_config_windows {
	BSPWM_FBC='#5294E2'
	BSPWM_NBC='#1E2128'
	BSPWM_ABC='#C778DD'
	BSPWM_PFC='#98C379'

	BSPWM_BORDER='1'
	BSPWM_SRATIO='0.50'
	BSPWM_GAP='10'

	bspc config border_width "$BSPWM_BORDER"
	bspc config split_ratio "$BSPWM_SRATIO"
	bspc config window_gap "$BSPWM_GAP"

	bspc config presel_feedback_color "$BSPWM_PFC"
	bspc config focused_border_color "$BSPWM_FBC"
	bspc config active_border_color "$BSPWM_ABC"
	bspc config normal_border_color "$BSPWM_NBC"

	bspc config single_monocle true
	bspc config borderless_monocle true
	bspc config gapless_monocle true

	bspc config automatic_scheme longest_side
	bspc config initial_polarity second_child
	bspc config center_pseudo_tiled true

	bspc config remove_disabled_monitors true
	bspc config remove_unplugged_monitors true
}

function bspc_config_pointer {
	bspc config focus_follows_pointer true
	bspc config presel_feedback true

	bspc config pointer_modifier control
	bspc config pointer_action2 resize_side
}

function bspc_config {
	bspc_config_windows
	bspc_config_pointer
}

# function resetall {
# 	killall -9 xsettingsd sxhkd dunst ksuperkey xfce4-power-manager bspc
	
# 	xsettingsd --config="$BSPDIR"/../bspwm.old/xsettingsd &
	
# 	if [[ ! `pidof xfce-polkit` ]]; then
# 		/usr/lib/xfce-polkit/xfce-polkit &
# 	fi

# 	bspc wm --adopt-orphans
# 	xsetroot -cursor_name left_ptr

# 	xfce4-power-manager &
	
# 	# CURTHEME="$(cat $BSPDIR/../bspwm.old/themes/.current)"
# 	# feh --no-fehbg --bg-fill "/home/thorolas/.config/bspwm.old/themes/$CURTHEME/wallpaper" 
# }

function update_shortcuts {
	sxhkd -c "$BSPDIR"/configuration/shortcuts/sxhkdrc &

	ksuperkey -e 'Super_L=Alt_L|F1' &
	ksuperkey -e 'Super_R=Alt_L|F1' &
}

init_workspaces
bspc_config
# bspc_rules

# resetall
update_shortcuts

# bspbar
# bspcomp
# bspdunst
# bspfloat &

# xsetroot -cursor_name left_ptr
# sxhkd -c $BSPDIR/sxhkdrc

# bspc config border_width 2
# bspc config window_gap 0

# bspc config split_ratio 0.5
# bspc config focus_follows_pointer true
# bspc config pointer_modifier mod1

# bspc config automatic_scheme spiral