#!/usr/bin/env bash

# shellcheck disable=1091
# shellcheck disable=2086
# shellcheck disable=2163

source "${0%/*}/locations"
export PATH="$PATH:$SCRIPTS/insanewm/"

locations.import toml
locations.import filesystem
locations.import terminal
locations.import process

BSPCONFIG="$CONFIGURATION/bspc/configuration.toml"
export _JAVA_AWT_WM_NONREPARENTING=1
export PATH="$PATH:$LIBRARIES"

function init_workspaces {
	workspaces=$(toml.getpropertylist "$BSPCONFIG" "workspaces.workspace")
	for monitor in `bspc query -M`; do bspc monitor "$monitor" -d $workspaces; done
}

function bspc_config {
	bspc_config_windows
	bspc_config_pointer
}

function bspc_config_windows {
	bspc config single_monocle true
	bspc config gapless_monocle true
	bspc config borderless_monocle true

	bspc config initial_polarity second_child
	bspc config automatic_scheme longest_side

	bspc config center_pseudo_tiled true
	bspc config remove_disabled_monitors true
	bspc config remove_unplugged_monitors true

	bspc config window_gap   "$(toml.getproperty "$BSPCONFIG" "windows.window-gap")"
	bspc config border_width "$(toml.getproperty "$BSPCONFIG" "windows.window-border")"
	bspc config split_ratio  "$(toml.getproperty "$BSPCONFIG" "windows.window-sratio")"

	bspc config normal_border_color   "$(toml.getproperty "$BSPCONFIG" "colors.normal-border")"
	bspc config active_border_color   "$(toml.getproperty "$BSPCONFIG" "colors.active-border")"
	bspc config focused_border_color  "$(toml.getproperty "$BSPCONFIG" "colors.focused-border")"
}

function bspc_config_pointer {
	bspc config presel_feedback true
	bspc config focus_follows_pointer true
	
	bspc config pointer_modifier control
	bspc config pointer_action2 resize_side

	bspc config presel_feedback_color "$(toml.getproperty "$BSPCONFIG" "colors.presel-feedback")"
}


function system_resetall {
	process.kill bspc
	process.kill picom
	process.kill sxhkd
	process.kill dunst
	process.kill polybar
	process.kill ksuperkey
	process.kill xsettingsd
	process.kill xfce4-power-manager
}

function system_initall {
	xfce4-power-manager &

	while read -r line; do terminal.runfile $line;
	done <<< "$(filesystem.getallfiles "$SCRIPTS/init/")";
}

function system_updateshortcuts {
	sxhkd -c "$BSPDIR"/configuration/sxhkd/sxhkdrc &
	ksuperkey -e 'Super_L=Alt_L|F1' &
	ksuperkey -e 'Super_R=Alt_L|F1' &
}

init_workspaces
bspc_config

system_resetall
system_updateshortcuts
system_initall