#!/usr/bin/env bash
# shellcheck disable=1090
# shellcheck disable=1091

BSPDIR="$(cd -- "$(dirname -- "${BASH_SOURCE[0]}")" &> /dev/null && pwd)"

LIBRARIES=$BSPDIR"/libraries"
UTILITIES=$BSPDIR"/utilities"
CONFIG_DIR=$BSPDIR"/configuration"
SCRIPTS_DIR=$BSPDIR"/scripts"

SHORTCUTS_DIR="$CONFIG_DIR/shortcuts"

export BSPDIR CONFIG_DIR SCRIPTS_DIR SHORTCUTS_DIR LIBRARIES UTILITIES

#usage add(utility)
function locations.import {
    source "$UTILITIES/$1";
}