#!/usr/bin/env bash

BSPDIR="$(cd -- "$(dirname -- "${BASH_SOURCE[0]}")" &> /dev/null && pwd)"

LIBRARIES=$BSPDIR"/libraries"
UTILITIES=$BSPDIR"/utilities"
CONFIG_DIR=$BSPDIR"/configuration"
SCRIPTS_DIR=$BSPDIR"/scripts"

SHORTCUTS_DIR="$CONFIG_DIR/shortcuts"

export BSPDIR CONFIG_DIR SCRIPTS_DIR SHORTCUTS_DIR LIBRARIES UTILITIES