#!/usr/bin/env bash

BSPDIR="$(cd -- "$(dirname -- "${BASH_SOURCE[0]}")" &> /dev/null && pwd)"

CONFIG_DIR="configuration"
SCRIPTS_DIR="scripts"

SHORTCUTS_DIR="$CONFIG_DIR/shortcuts"

export BSPDIR CONFIG_DIR SCRIPTS_DIR SHORTCUTS_DIR